application: legitapi
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
  - remote_api: on
  - deferred: on

libraries:
- name: pycrypto
  version: "2.3"
  
- name: webapp2
  version: "latest"

inbound_services:
- warmup

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.app
  login: admin

- url: /api/v1/.*
  secure: always
  script: api.app
  
- url: /sandbox/v1/.*
  secure: always
  script: api.app
  
- url: /.*
  secure: always
  script: devsite.app
  
  
  
  
  
  
  
  
